spring.application.name=oddsapi
api.key=5ff17e3a784aec7e4f83b1c2a149b77a
spring.datasource.url=jdbc:postgresql://localhost:5432/oddsdb
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true