spring.application.name=oddsapi
api.key=11f6f55d9f52fea0b1e1ed1e819ed03b
spring.datasource.url=jdbc:postgresql://localhost:5432/oddsdb
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true